FROM golang:1.26.4-alpine AS builder

RUN go install github.com/pressly/goose/v3/cmd/goose@v3.27.1

FROM alpine:3.20

COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY migrations /migrations

ENTRYPOINT ["goose", "up"]
