// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID          pgtype.UUID
	ServiceName string
	Price       int32
	UserID      pgtype.UUID
	StartDate   pgtype.Timestamptz
	EndDate     pgtype.Date
}
