// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (
    id,
    service_name,
    price,
    user_id,
    start_date,
    end_date
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateSubscriptionParams struct {
	ID          pgtype.UUID
	ServiceName string
	Price       int32
	UserID      pgtype.UUID
	StartDate   pgtype.Timestamptz
	EndDate     pgtype.Date
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, service_name, price, user_id, start_date, end_date FROM subscriptions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSubscription(ctx context.Context, id pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE subscriptions
SET
    service_name = $2,
    price = $3,
    user_id = $4,
    start_date = $5,
    end_date = $6
WHERE id = $1
RETURNING id, service_name, price, user_id, start_date, end_date
`

type UpdateSubscriptionParams struct {
	ID          pgtype.UUID
	ServiceName string
	Price       int32
	UserID      pgtype.UUID
	StartDate   pgtype.Timestamptz
	EndDate     pgtype.Date
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}
